# Generated by Django 3.1.4 on 2021-01-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210106_0055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VirtualTour',
        ),
    ]
